### PR TITLE
chore: add sol-headers

### PR DESCRIPTION
**Pull request by ahmedali8**
npm package inspired by transmissions11's [`headers`](https://github.com/transmissions11/headers)

Hey @paulrberg, what do you think should this be a part of this repo or not?

if not then you can surely close this PR

### CODE REVIEW

**Comment by ahmedali8** [comment]
Link to the package: [sol-headers](https://www.npmjs.com/package/sol-headers)

**Comment by paulrberg** [comment]
Hi Ahmed, thanks for your PR. Also great work with that `sol-headers` package.

But I'd prefer not to force the users of this template to use VSCode, so I'm going to close this PR.

**Comment by ahmedali8** [comment]
Thanks!

what if we only add it as a package (sol-headers) and no tasks.json so that people using this repo could use it through command line or is it a bad idea?

**Comment by paulrberg** [comment]
Well that would be a superfluous package because it's not used anywhere in the template itself.

I'd prefer the template to remain clean and minimalistic.

**Comment by ahmedali8** [comment]
Alright great!
Thanks @paulrberg

**Pull request closed without merging**
