### PR TITLE
removed hardhat-deploy due to compilation issue

### PR DESCRIPTION
**Pull request by njelich**
Fixes https://github.com/PaulRBerg/hardhat-template/issues/186

But removes hardhat-deploy plugin, and thus breaks deployment scripts. Feel free to repurpose.

Might be resolved anyway by upstream PR on hardhat-deploy https://github.com/wighawag/hardhat-deploy/pull/511

@PaulRBerg it's up to you what you want to do, but I suggest removing hardhat-deploy support for now

### CODE REVIEW

**Comment by PaulRBerg** [comment]
Thanks for your PR.

Let's wait for that PR upstream to be resolved.

**Comment by njelich** [comment]
I'd recommend against that, its not moving particularly fast and main branch is currently broken.

**Comment by PaulRBerg** [comment]
Got it, in this case, I'll review later.

Quick question - how difficult would it be to refactor the deployment script to make it work without hardhat-deploy?

**Comment by PaulRBerg** [comment]
I have merged this to unblock the issue.

**Pull request merged**
