### PR TITLE
refactor: replace greeter with lock contract

### PR DESCRIPTION
**Pull request by zikyfranky**
This is a PR for the #141 issue

### CODE REVIEW

**Comment by zikyfranky** [comment]
Let me know if there's any refactoring needed @PaulRBerg 

Compliments of the season.

**Comment by PaulRBerg** [comment]
Thanks for the PR, @zikyfranky. I wanted to push some changes to your fork but it looks like you didn't give me permission to do that?

https://app.warp.dev/block/TcqJ9dWwVISwoSJAjK57ot

**Comment by zikyfranky** [comment]
I have "Allow edits by maintainers" enabled, isn't that supposed to give you write access?

Screenshot 2023-12-25 at 7 09 39 PM

Anyways, if that's not the case, how do I grant you access without explicitly adding you as a collaborator?

I did send you an invite should that be the only route possible

**Comment by PaulRBerg** [comment]
"Allow edits by maintainers" works only for non-main branches. You made your changes directly on `main`.

Thanks for giving me access.

**Comment by PaulRBerg** [comment]
I'm still not able to push it to your fork, and I don't know why. Can you cherry-pick the changes from this branch, please?

https://github.com/PaulRBerg/hardhat-template/tree/zikyfranky-main

**Comment by zikyfranky** [comment]
@PaulRBerg Should be good now.

**Pull request merged**
